<h2>Module Fired </h2>

<!---->
<?php
//
//use Magento\Sales\Model\ResourceModel\Order\CollectionFactory;
//
//public function __construct(
//    CollectionFactory $orderCollectionFactory
//    ) {
//        $this->orderCollectionFactory = $orderCollectionFactory;
//    }
//
//    public function test()
//    {
//
//    $customerEmail="testcustomer@mycoolshop.com";
//    $total=0;
//    $orders = $this->orderCollectionFactory->create()
//    ->addAttributeToFilter('customer_email', $customerEmail);
//    foreach ($orders as $order) {
//    echo "Order# {$order->getIncrementId()} - Creation Date: {$order->getCreatedAt()} - Value: {$order->getGrandTotal()}". PHP_EOL;
//    $total=$total+$order->getGrandTotal();
//    }
//    echo "Total for customer:".$total.PHP_EOL;
//
//
//    }
//?>