<!--<div class="callfor-popup">-->
<!--    <h2>Account Limit</h2>-->
<!--    <p>Hello {{ name }} Unfortunately You have reached the allocated purchase limit of £500</p>-->
<!--    <p>Please refer to the <a href="/staff-account-terms">Terms</a> for more information</p>-->
<!---->
<!---->
<!--</div>-->
<!--<script>-->
<!--    require(-->
<!--        [-->
<!--            'jquery',-->
<!--            'Magento_Ui/js/modal/modal'-->
<!--        ],-->
<!--        function (-->
<!--            $,-->
<!--            modal-->
<!--        ) {-->
<!--            var modaloption = {-->
<!--                type: 'popup',-->
<!--                modalClass: 'modal-popup',-->
<!--                responsive: true,-->
<!--                innerScroll: true,-->
<!--                clickableOverlay: true,-->
<!--                title: 'Staff Account Limit'-->
<!--            };-->
<!--            var callforoption = modal(modaloption, $('.callfor-popup'));-->
<!--            $('.callfor-popup').modal('openModal');-->
<!--        }-->
<!--    );-->
<!--</script>-->